"""Builds and writes the PDF pitch report using fpdf2, assembling all analysis sections."""

from fpdf import FPDF


class PitchOSReport(FPDF):
    """A4 portrait PDF report with branded header/footer and structured section layout."""

    # Brand palette
    NAVY      = (26, 43, 74)       # #1a2b4a — header bar
    WHITE     = (255, 255, 255)
    GREY_BG   = (232, 232, 232)    # section title band
    GREY_TEXT = (120, 120, 120)    # footer / muted labels
    DARK_TEXT = (40, 40, 40)

    # Column widths for two-column tables (left label + right value)
    COL_LABEL = 55
    COL_VALUE = 125

    def __init__(self, acquirer_ticker: str, target_ticker: str) -> None:
        # 22mm top margin gives header (16mm bar) + 6mm breathing room before content
        super().__init__(orientation="P", unit="mm", format="A4")
        self.set_margins(left=15, top=22, right=15)
        self.set_auto_page_break(auto=True, margin=18)
        self._deal_label = f"{acquirer_ticker.upper()} → {target_ticker.upper()}"

    # ── fpdf2 page hooks ──────────────────────────────────────────────────────

    def header(self) -> None:
        """Dark navy bar across the full page width with report title and deal label."""
        # Full-width navy rectangle (x=0 so it bleeds to the edge, not the margin)
        self.set_fill_color(*self.NAVY)
        self.rect(0, 0, 210, 16, style="F")

        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.WHITE)

        # Left: report title
        self.set_xy(15, 5)
        self.cell(100, 6, "PitchOS  |  M&A Rationale Report", align="L")

        # Right: deal label (acquirer → target)
        self.set_xy(0, 5)
        self.cell(195, 6, self._deal_label, align="R")

        # Reset text colour; cursor lands at top-margin start
        self.set_text_color(0, 0, 0)

    def footer(self) -> None:
        """Page number left, attribution right, in small grey text."""
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*self.GREY_TEXT)
        self.cell(0, 6, f"Page {self.page_no()}", align="L")
        self.set_y(-12)
        self.cell(0, 6, "Generated by PitchOS", align="R")
        self.set_text_color(0, 0, 0)

    # ── layout helpers ────────────────────────────────────────────────────────

    def render_section_title(self, title: str) -> None:
        """Light grey background band with bold dark section title."""
        self.set_fill_color(*self.GREY_BG)
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.DARK_TEXT)
        self.cell(0, 8, f"  {title}", border=0, new_x="LMARGIN", new_y="NEXT",
                  align="L", fill=True)
        self.ln(2)
        self.set_text_color(0, 0, 0)
